src/Perlink.Web/Models/ErrorViewModel.cs
using System;

namespace Perlink.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Perlink.Web/Models/LawViewModel.cs
using Perlink.Data.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace Perlink.Web.Models
{
    public class LawViewModel
    {
        public string NumeroDoProcesso { get; set; }
        public DateTime dataDeCriacaoDoProcesso { get; set; }
        public decimal valor { get; set; }
        public Lawoffice escritorio { get; set; }
        public int escritorioId { get; set; }
    }
}

src/Perlink.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Perlink.Web.Models;

namespace Perlink.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Perlink.Web/Controllers/MainController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Results;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Perlink.Data.Data;
using Perlink.Services;
using Perlink.Services.Base;
using Perlink.Web.Models;

namespace Perlink.Web.Controllers
{

    public class MainController : Controller
    {
        public MainService _service;

        public MainController(MainService service)
        {
            _service = service;
        }

        // GET: Main
        public async Task<ActionResult> Index()
        {
            var suits = _service.GetLawsuitList();
            return View(suits);
        }

        // GET: Main/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Main/Create
        public ActionResult Create()
        {
            return View();
        }

        
        public IActionResult Create(LawViewModel lawViewModel)
        {
            if (lawViewModel != null)
            {
                Lawsuit lawsuit = new Lawsuit();
                //lawsuit.SuitNumber = lawViewModel.numeroDoProcesso;
                //lawsuit.CourtCosts = lawViewModel.valor;
                //lawsuit.LawofficeId = lawViewModel.escritorioId;
                //lawsuit.SuitCreationTime = lawViewModel.dataDeCriacaoDoProcesso;

                var result = _service.Create(lawsuit);
                if (result == ServiceEnums.CreateState.Success)
                {
                    //return Created("", lawViewModel);
                }
            }

            //return RedirectToAction("Index", lawViewModel);
            return BadRequest();
        }

        // GET: Main/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Main/Edit/5
        [Microsoft.AspNetCore.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Main/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Main/Delete/5
        [Microsoft.AspNetCore.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

src/Perlink.Web/Controllers/api/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using Perlink.Data.Data;
using Perlink.Services;
using Perlink.Services.Base;
using Perlink.Web.Models;
using Perlink.Web.Validations;
using FromBodyAttribute = Microsoft.AspNetCore.Mvc.FromBodyAttribute;

namespace Perlink.Web.Controllers.api
{
    public class MainController : ApiController
    {
        public MainService _service;

        public MainController(MainService service)
        {
            _service = service;
        }

        [Microsoft.AspNetCore.Mvc.Route("api/[controller]")]
        [Microsoft.AspNetCore.Mvc.HttpPost]
        public IHttpActionResult Create([FromBody] LawViewModel lawViewModel)
        {
            
            var validation = new MainValidator().Validate(lawViewModel);

            if (validation.IsValid)
            {
                Lawsuit ls = new Lawsuit();
                ls.SuitNumber = lawViewModel.NumeroDoProcesso;
                ls.SuitCreationTime = lawViewModel.dataDeCriacaoDoProcesso;
                ls.CourtCosts = lawViewModel.valor;
                ls.LawofficeId = lawViewModel.escritorioId;

                var result = _service.Create(ls);
                if (result == ServiceEnums.CreateState.Success)
                {
                    return Ok(result);
                }

                return StatusCode(HttpStatusCode.PartialContent);
            }

            return BadRequest();
        }
    }
}

src/Perlink.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/Perlink.Web/Views/Main/Index.cshtml
@model IEnumerable<Perlink.Data.Data.Lawsuit>

@{
    ViewData["Title"] = "Index";
}

<table class="table">
    <thead>
        <tr>
            <th>
                <span class="text-info">Numero do Processo</span>
            </th>
            <th>
                <span class="text-info">Data de Criação do Processo</span>
            </th>
            <th>
                <span class="text-info">Valor do Processo</span>
            </th>
            <th>
                <span class="text-info">Escritorio Responsável</span>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SuitNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SuitCreationTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourtCosts)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lawoffice.Name)
            </td>
        </tr>
}
    </tbody>
</table>

src/Perlink.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Perlink.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Perlink.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Main" asp-action="Index">Relatorio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Perlink.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
<script>
    setInterval(function() {
        window.location.reload();
    }, 10000);
</script>

@RenderSection("Scripts", required: false)
</body>
</html>